`CREATE TABLE IF NOT EXISTS USER (
	UserId INT PRIMARY KEY AUTO_INCREMENT,
    UserName VARCHAR(50) NOT NULL,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(25) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedTimeStamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    DeletedTimeStamp DATETIME
);`